import { App } from 'vue'
import { createRouter, createWebHistory } from 'vue-router'
import { getCurrentUser } from '/~/logics'
// import routes generated by Voie
import routes from 'voie-pages'
// progress bar
import NProgress from 'nprogress'

export default (app: App) => {
  const router = createRouter({
    history: createWebHistory(),
    routes,
  })

  router.beforeEach(async (to, from, next) => {
    NProgress.start()
    if (to.name !== 'login' && !await getCurrentUser()) next({ name: 'login' })
    else next()
  })
  router.afterEach(() => { NProgress.done() })

  app.use(router)
}
